server:
  port: 16000
spring:
  application:
    name: cart-service
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 100
        max-idle: 200
        max-active: 300
        max-wait: 3000ms
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳续约
    lease-expiration-duration-in-seconds: 15 #15秒后无心跳提出服务
#jwt的属性配置
shopping:
  jwt:
    secret: maguojwtlogin # 登录校验的密钥---------通过成公钥、私钥时，混合的数据
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: shopping-token #cookie的名称

