server:
  port: 10000
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 1MB #单个文件大小最大1MB
      max-request-size: 10MB #上传时，所有文件总和不能超过10MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

up:
  file-path: E:\\TestImg\\FastDfs\\up