server:
  port: 8000
spring:
  application:
    name: item-service
  #数据库的配置
  datasource:
    url: jdbc:mysql:///j64_shopping
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳续约
    lease-expiration-duration-in-seconds: 15 #15秒无心跳剔除服务

#给实体类指定别名
mybatis:
  type-aliases-package: org.java.shopping.entity